# General settings
name: 'graph-tf-model'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'online'             # online | offline | disabled
gpus: 1                     # Multi-gpu is not implemented on this branch

resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null         # Use absolute path

check_val_every_n_epochs: 5
sample_every_val: 4
val_check_interval: null
samples_to_generate: 512       # We advise to set it to 2 x batch_size maximum
samples_to_save: 20
chains_to_save: 1
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif

# Test
generated_path: null
final_model_samples_to_generate: 10000
final_model_samples_to_save: 30
final_model_chains_to_save: 20
num_sample_fold: 1
evaluate_all_checkpoints: False
save_samples: True  # Save samples at the final test step or not, normally only used at the last epoch or during inference

# Conditional Generation
conditional: False
target: 'k2' 
guidance_weight: 2.0
