# Training settings
n_epochs: 1000
lr: 0.0002
clip_grad: null          # float, null to disable
save_model: True
batch_size: 256
num_workers: 0
ema_decay: 0           # 'Amount of EMA decay, 0 means off. A reasonable value  is 0.999.'
progress_bar: false
weight_decay: 1e-12
optimizer: adamw # adamw,nadamw,nadam => nadamw for large batches, see http://arxiv.org/abs/2102.06356 for the use of nesterov momentum with large batches
seed: 0
# Model settings

transition: 'marginal'                          # uniform or marginal
model: 'graph_tf'
diffusion_noise_schedule: 'cosine'              # 'cosine', 'polynomial_2'

extra_features: null       # 'all', 'cycles', 'eigenvalues' or null

# Do not set hidden_mlp_E, dim_ffE too high, computing large tensors on the edges is costly
# At the moment (03/08), y contains quite little information
hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}

# The dimensions should satisfy dx % n_head == 0
hidden_dims : {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}

name: 'aig' # Override default 'graph-tf-model' from general_default.yaml [cite: cvignac/DiGress/DiGress-780242b8d3e7d78316bb5cf90c639fb0cd4c6079/configs/general/general_default.yaml]

abs_path_to_project_root: "." # Or provide via command line.
gpus: 1
wandb: 'online'
resume: null
test_only: null

# --- Settings for intermediate validation and sampling ---
check_val_every_n_epochs: 50     # Override default 5 [cite: cvignac/DiGress/DiGress-780242b8d3e7d78316bb5cf90c639fb0cd4c6079/configs/general/general_default.yaml]. For 5000 epochs, this is 200 validations.
# --- Settings for final model sampling (after training) ---
final_model_samples_to_generate: 1000 # User requirement. Overrides default 10000 from general_default.yaml [cite: cvignac/DiGress/DiGress-780242b8d3e7d78316bb5cf90c639fb0cd4c6079/configs/general/general_default.yaml].
final_model_samples_to_save: 50       # Number of the 1000 to visualize directly by framework. Default is 30 [cite: cvignac/DiGress/DiGress-780242b8d3e7d78316bb5cf90c639fb0cd4c6079/configs/general/general_default.yaml]. All 1000 are typically saved programmatically.
      # Default from general_default.yaml [cite: cvignac/DiGress/DiGress-780242b8d3e7d78316bb5cf90c639fb0cd4c6079/configs/general/general_default.yaml].
type: 'discrete'
diffusion_steps: 1000 # Override default 500 from model/discrete.yaml [cite: cvignac/DiGress/DiGress-780242b8d3e7d78316bb5cf90c639fb0cd4c6079/configs/model/discrete.yaml].

n_layers: 8 # Override default 5 from model/discrete.yaml [cite: cvignac/DiGress/DiGress-780242b8d3e7d78316bb5cf90c639fb0cd4c6079/configs/model/discrete.yaml].

lambda_train: [1.0, 1.0, 0.0] # Override default [5,0] [cite: cvignac/DiGress/DiGress-780242b8d3e7d78316bb5cf90c639fb0cd4c6079/configs/model/discrete.yaml]. Weights for X, E, y losses respectively.


sample_every_val: 4
val_check_interval: null
samples_to_generate: 512       # We advise to set it to 2 x batch_size maximum
samples_to_save: 20
chains_to_save: 1
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif

final_model_chains_to_save: 20
#final_model_samples_to_generate: 3
#final_model_samples_to_save: 2
#final_model_chains_to_save: 1

evaluate_all_checkpoints: False