defaults:
    - _self_
    - general : general_default
    - model : discrete
    - train : train_default
    - dataset : qm9
    - sample : sample_default

hydra:
  job:
    chdir: True
  run:
    dir: ./

